### PR TITLE
Observable not working for me

### PR DESCRIPTION
**Pull request by AndrewSB**
For some reason what you had wasn't working for me.

I checked using RxSwift's `.debug` operator, and I saw that the Observable was being subscribed to, but no `.next` events.
Adding this got the next events going, but I feel as if I'm missing something.

I opened this PR more as a discussion on why it didn't work for me, not to get this merged in (assuming this library is currently functional)

FYI: I ran this in swift 3, with RxSwift 3.0.1. So there were some other updates I made, but they were minor

### CODE REVIEW

**Comment by DivineDominion** [comment]
I think creating a custom `Observable`, then inside subscribing to another "subject" and using a custom dispose bag, is [the code smell RxSwift warns us of.](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Tips.md) I'll have a closer look ...

**Comment by DivineDominion** [comment]
Seems there's no other way (:

Can you see if my branch the trick for you, too? I added integration tests to verify the faulty behavior and changed a few details.
https://github.com/DivineDominion/rxreswift/tree/swift3-carthage

**Comment by AndrewSB** [comment]
I'll check it out 😄

**Comment by AndrewSB** [comment]
this is an anti pattern, so I'm going to delete my fork. Thanks @DivineDominion

**Comment by DivineDominion** [comment]
Huh, can you explain?

**Comment by AndrewSB** [comment]
I was just agreeing with your assessment that my change was a bad code smell, so we probably shouldn't merge it in!

**Pull request closed without merging**
